### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by vigneshkindia** [ryankurte/winston-cluster#1]
Hi,
The example that you have provided in the ReadMe doesnt work for me.

Thanks.

**Comment by ryankurte** [comment]
Hey there,

Updated the example and it works for me, let me know if you still have any issues.

Regards,

Ryan

**Comment by vigneshkindia** [comment]
Hi,
The example is working fine. I am using a custom logger and i am not able to get it to work. 

here is my code.

var cluster = require('cluster');
var winston = require('winston');
var winstonCluster = require('winston-cluster');

if(cluster.isMaster) {
    var cpuCount = require('os').cpus().length;

	var logger = new (winston.Logger)({
            transports : [
                new (winston.transports.DailyRotateFile)({
                    filename    : 'dummy.log',
                    datePattern : '.dd-MM-yyyy',
                    json        : true,
                    timestamp   : true
                })
            ]
        }); 

    for (var i = 0; i < cpuCount; i += 1) {
        cluster.fork();
    }
	
    winstonCluster.bindListeners();

} else {
    winstonCluster.bindTransport();
    logger.error('info', 'Hello distributed log files!'+ cluster.worker.id);
}
