### ISSUE TITLE
API Key in Public Repo?

### ISSUE THREAD

**Issue by ralphschuler** [ryankurte/winston-cluster#21]
Hey @ryankurte,

just to be sure: is it correct that the API Key is readable by everyone?
Should't that be a secret in Travis CI?

https://github.com/ryankurte/winston-cluster/blob/c035839a1d3adf7856b17beb13f54de493770ed8/.travis.yml#L13

greetings
Ralph

**Comment by ryankurte** [comment]
hi @ralphschuler, that's not a raw API key, the `secure` part means it's stored in an [encrypted](https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml) form that only travis-ci can decrypt to use

**Comment by ralphschuler** [comment]
ahh Okay.

by bad :)
