### ISSUE TITLE
Project Maintenance

### ISSUE THREAD

**Issue by ralphschuler** [ryankurte/winston-cluster#23]
Hey,

i was wondering if you might be Interested in handing over the project.
Im using it in my daily work and would be more than happy to continue development of this module.

I know the last weeks and months have shown serious trust issues in regards to handing over a project.
Im happy to provide you a valid proof of my identity to overcome the trust issues.

My first and until this day only contribution to this project was back in 2019 when i ported it to winston3.

let me know if your interested, and if not im sorry to take your time.

**Comment by ryankurte** [comment]
howdy, you've probably gathered i haven't used this in a while 😅 i'd be happy to start by adding you as a maintainer here and on NPM if that'd work for you?

**Comment by ralphschuler** [comment]
Hey :)

i might have had a idea  ;)

im totally happy being added as a maintainer.
like i said im happy to prove im not some yerk.

**Comment by ryankurte** [comment]
sweet as, i've added you here and on npm ^_^

**Comment by ralphschuler** [comment]
> sweet as, i've added you here and on npm ^_^

noice.
one more thing.
which account did you add on NPM?
mine is ~ralphschuler had to create one.

**Comment by ryankurte** [comment]
ahh, i added that but npm didn't tell me anything was wrong... should be there now.
