### ISSUE TITLE
Upgrade to the latest version of winston

### ISSUE THREAD

**Issue by ImmortalRat** [ryankurte/winston-cluster#3]
Hey, you are still using winston 1.0.0, and the dependency is done as "^1.0.0", which makes it incompatible with 2.0.0. Because of that "your" winston and "my" winston are actualy two different modules, that come from 2 different folders, and so "your" configuration of winston does not apply to "mine", thus logging happens only in console regardless of what transports I am using.

I recommend to use ">=1.0.0" as a dependency version.

**Comment by ryankurte** [comment]
I feel that >= is a bit broad, so have updated to the latest version of winston in v0.1.* and enabled greenkeeper.io to keep track of it.
Does thats solve your issue?

**Comment by ImmortalRat** [comment]
yes, thank you, that solved my issue.
